### ISSUE TITLE
Feature Toggle UI

### ISSUE THREAD

**Issue by jwicks31** [paralleldrive/react-feature-toggles#173]
It'd be nice to have a floating box that

displays all the possible feature toggles,
displays their current state,
allows changing that state (maybe using history api to just change the query param dynamically?)
I'm thinking we could have this floating box show automatically when the ft query param is present, even if its empty.

Could also hide it behind a keyboard shortcut, or both.

If we wanted a floating box, it'd be nice to make it draggable so we can move it around to avoid it shadowing parts of the screen.

Or it could be a drop-down in the footer.

**Comment by kennylavender** [comment]
I have a few concerns about adding a UI.

* We can't show available features to enable from the UI, Eric purposly made sure I avoided exposing features to the user that could be enabled.
* We don't want to show features that are currently active by default because we don't want those turned off.
* So really we would only be showing features activated by the query, it could just be a convenient way of disabling them if they are in local storage.
Dev UI's, I've always liked the idea, but always had issues with implementation. Have yet to see a dev UI's that succeeds in staying out of the way and does not interfere with theming/design, that includes overlays and header/footer UI's.

**Comment by kennylavender** [comment]
I don't think this is a good idea and I think its out of the scope of this library. It could be implemented outside of this library.
